### ISSUE TITLE
Updating README for vcf generation? And general question.

### ISSUE THREAD

**Issue by charlesfoster** [TurakhiaLab/rivet#2]
Hi,

The README says: "Please see the following workflow to [create a VCF](https://github.com/TurakhiaLab/rivet/blob/main/docs/create_vcf.md) for uploading to RIVET locally." This link is currently dead. Are there some instructions prepared to describe how to create the VCF file locally? From reading `run_ripples_filtration.sh`, I believe that least the first command may be `matUtils extract -i $mat -s filtering/data/allRelevantNodeNames.txt -v filtering/data/allRelevantNodes.vcf -T 10`. Is this correct? And is it possible to run the frontend without running the `rivet` pipeline using the results from `ripples`, or is that not recommended?

Finally, are there any plans to enable running `rivet` entirely locally without using Google Cloud?

Thanks,
Charles

**Comment by mrkylesmith** [comment]
Hi Charles, 

Thanks for the issue!  You are correct, `matUtils extract` is the command to use and I have updated the link to [create a VCF](https://github.com/TurakhiaLab/rivet/blob/main/docs/create_vcf.md) so please see that page for specific details on generating a VCF that can be uploaded to the RIVET frontend locally. 

Yes it is possible to run the RIVET frontend locally (with reduced functionality compared to [https://rivet.ucsd.edu/](https://rivet.ucsd.edu/)) with results from `ripples` ( we recommend using `ripples-fast`), although you will need to rearrange the columns of the `recombinants.tsv` output file from `ripples`.  The RIVET frontend requires an input tab-delimited results file `(-r)` with the first 3 columns being the `recombinant node id` \t `donor node id` \t `acceptor node id`.  Please see this section of the readme: [Viewing your own recombinants with RIVET on a local HTTP server
](https://github.com/TurakhiaLab/rivet#rivet_local)

For more information on the quality control and filtration pipeline that is part of the RIVET backend, please see our [About page](https://rivet.ucsd.edu/about) and also [Pandemic-scale phylogenomics reveals the SARS-CoV-2 recombination landscape](https://www.nature.com/articles/s41586-022-05189-9), which provides more details. 

And yes, we do plan to support this, the ability to do this should be available to users by next week (along with a few other new features), stay tuned! 

Best, 
Kyle

**Comment by charlesfoster** [comment]
Thanks for the info. I'll stay tuned!
