### ISSUE TITLE
ENH: Add number of children below each node (both for donors and recombinant)

### ISSUE THREAD

**Issue by corneliusroemer** [TurakhiaLab/rivet#5]
It'd be nice if the summary table listed the number of children below each node of:
- donor 1
- donor 2
- recombinant

I tried to find this in the table but couldn't.

In particular, I'd love to be able to filter by number of children below an identified recombinant node. Everything above say 50 is definitely worth investigating for example, but singlets less so. This information might already be subsumed in the recombination score, but it'd be nice to see the raw data as well.

**Comment by mrkylesmith** [comment]
Hi @corneliusroemer !

Thanks for the suggestion!  In our latest results, I've added three additional columns to the table, named "Recomb Number Samples", "Donor Number Samples", "Acceptor Number Samples".  The table can be sorted by a column value by clicking the column header of interest.

Please feel free to let us know if you have any additional suggestions or questions!

**Comment by mrkylesmith** [comment]
Hi @corneliusroemer.  Please feel free to reach out or open additional issues if you would like to see additional functionality or have further suggestions on how to improve RIVET with respect to this enhancement.  Thanks for your feedback!
