### ISSUE TITLE
ENH: Publish machine readable table with all strain names of inferred recombinants, for quick search 

### ISSUE THREAD

**Issue by corneliusroemer** [TurakhiaLab/rivet#6]
Currently, the way most people identify recombinants for Pango designation is manually via e.g. Nextclade's private mutation score or other tools. It'd be nice if one could quickly look up a strain in a database of suspected recombinants inferred by Ripples/Rivet.

There's currently a single "representative descendant", but that's not helpful when one has only identified a single suspected recombinant. For that case, one would want _all_ descendants in a tsv to quickly `ctrl+f` or grep for it.

This shouldn't be technically difficult, simply extracting the strain names from the usher tree below a recombinant node and pushing it to Github, or another site.

At least for open data this should be no problem.

**Comment by yatisht** [comment]
I think we discussed this already, but it is possible to view the descendants of any node (recombinant, acceptor or donor) in the SNV view by clicking on the label next to the sequence as explained here: https://www.youtube.com/watch?v=XelRL3qJlD0&t=108s&ab_channel=KyleSmith.

You can also download a complete set of descendants in a tsv file using the "Download All Descendants" button on the top-left corner of the page.

**Comment by mrkylesmith** [comment]
Hi, @corneliusroemer.  Does this solve your issue?  Is there any additional functionality you would like to see for this use case?

Also, you can search the full tree results by EPI identifer in the search bar, by first selecting the toggle button "Search by Sample/EPI Identifier".  This will filter the results table to show only inferred recombinant ancestry of the given sample, if any.
