### ISSUE TITLE
Missing samples_descend.txt file of Full Tree?

### ISSUE THREAD

**Issue by fgmp** [TurakhiaLab/rivet#9]
The “samples_descendants.txt” file that downloads upon clicking Download All Descendants seems to be the same file whether I select Full Tree or Public Tree. 

The first listed nodes from the two files are the same. 
Full Tree:
<img width="1280" alt="fullTreeSamplesDescNodes" src="https://github.com/TurakhiaLab/rivet/assets/26614960/20d30c79-4676-4039-8034-b688a67d489e">

Public Tree:
<img width="1280" alt="publicTreeSamplesDescNodes" src="https://github.com/TurakhiaLab/rivet/assets/26614960/ac8fa5f5-b664-473a-9034-1ef05bc3f464">

Also, I could not find Full Tree recombinant nodes on any of the two samples_descendants.txt files, but I can find Public Tree recombinant nodes on both of them. 

Can the samples_descendants.txt file for the Full Tree be made downloadable? I was hoping to parse it using nodes from its matching final_recombinants_YYYY-MM-DD.txt file.

**Comment by mrkylesmith** [comment]
Hi @fgmp.  Sure, thank you for pointing out this issue, it should be fixed now with the latest update and you can download the full tree descendants by clicking the "Download All Descendants" button on the "Full Tree" tab.  Please feel free to let us know if you experience any issues with this, or have any other feature requests you would like to see.  Thank you!
